# Generated by Django 5.2.17 on 2026-09-27 21:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PROCESSANDO_IA', 'Processando IA'), ('ERRO_PROCESSAMENTO', 'Erro de processamento'), ('CONCLUIDA', 'Concluída')], default='DRAFT', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('nota_geral', models.FloatField(blank=True, null=True)),
                ('nivel_maturidade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apta', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PontuacaoDimensao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.FloatField(help_text='De 0 a 100.')),
                ('prioritaria', models.BooleanField(default=False)),
                ('delta_percentual', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'pontuação por dimensão',
                'verbose_name_plural': 'pontuações por dimensão',
                'ordering': ['dimensao__ordem'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_objetivo', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('texto_aberto', models.TextField(blank=True)),
                ('feedback_ia', models.JSONField(blank=True, null=True)),
                ('tentativas_ia', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
