# Generated by Django 5.2.17 on 2026-09-27 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('contas', '0001_initial'),
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='contas.empresa'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='questionarios.questionario'),
        ),
        migrations.AddField(
            model_name='pontuacaodimensao',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='avaliacoes.avaliacao'),
        ),
        migrations.AddField(
            model_name='pontuacaodimensao',
            name='dimensao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='questionarios.dimensao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacoes.avaliacao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='questionarios.pergunta'),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('empresa',), name='um_rascunho_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='pontuacaodimensao',
            constraint=models.UniqueConstraint(fields=('avaliacao', 'dimensao'), name='uma_pontuacao_por_dimensao'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.UniqueConstraint(fields=('avaliacao', 'pergunta'), name='uma_resposta_por_pergunta'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.CheckConstraint(condition=models.Q(('valor_objetivo__isnull', True), models.Q(('valor_objetivo__gte', 1), ('valor_objetivo__lte', 5)), _connector='OR'), name='valor_objetivo_na_escala'),
        ),
    ]
