# Generated by Django 5.2.17 on 2026-09-27 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('versao', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'questionário',
                'ordering': ['-data_criacao', '-versao'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('ativo',), name='um_questionario_ativo')],
            },
        ),
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('peso', models.FloatField(help_text='Peso da dimensão no índice geral de prontidão.')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensoes', to='questionarios.questionario')),
            ],
            options={
                'verbose_name': 'dimensão',
                'verbose_name_plural': 'dimensões',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('OBJETIVA', 'Objetiva'), ('DISSERTATIVA', 'Dissertativa')], max_length=20)),
                ('peso', models.FloatField(help_text='Peso da pergunta dentro da dimensão.')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('dimensao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='questionarios.dimensao')),
            ],
            options={
                'ordering': ['ordem'],
                'constraints': [models.CheckConstraint(condition=models.Q(('peso__gt', 0)), name='pergunta_peso_positivo')],
            },
        ),
        migrations.AddConstraint(
            model_name='dimensao',
            constraint=models.CheckConstraint(condition=models.Q(('peso__gt', 0)), name='dimensao_peso_positivo'),
        ),
        migrations.AddConstraint(
            model_name='dimensao',
            constraint=models.UniqueConstraint(fields=('questionario', 'nome'), name='dimensao_nome_unico_na_versao'),
        ),
    ]
